<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Explore Red Wine Data</title>

<script src="udacity_dand-p4-explore-and-summarize-data_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="udacity_dand-p4-explore-and-summarize-data_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="udacity_dand-p4-explore-and-summarize-data_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="udacity_dand-p4-explore-and-summarize-data_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="udacity_dand-p4-explore-and-summarize-data_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="udacity_dand-p4-explore-and-summarize-data_files/navigation-1.1/tabsets.js"></script>
<link href="udacity_dand-p4-explore-and-summarize-data_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="udacity_dand-p4-explore-and-summarize-data_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Explore Red Wine Data</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li><a href="#univariate-exploration"><span class="toc-section-number">2</span> Univariate Exploration</a><ul>
<li><a href="#quality"><span class="toc-section-number">2.1</span> Quality</a></li>
<li><a href="#fixed-acidity"><span class="toc-section-number">2.2</span> Fixed Acidity</a></li>
<li><a href="#volatile-acidity"><span class="toc-section-number">2.3</span> Volatile Acidity</a></li>
<li><a href="#citric-acid"><span class="toc-section-number">2.4</span> Citric Acid</a></li>
<li><a href="#residual-sugar"><span class="toc-section-number">2.5</span> Residual Sugar</a></li>
<li><a href="#chlorides"><span class="toc-section-number">2.6</span> Chlorides</a></li>
<li><a href="#free-sulfur-dioxide"><span class="toc-section-number">2.7</span> Free Sulfur Dioxide</a></li>
<li><a href="#total-sulfur-dioxide"><span class="toc-section-number">2.8</span> Total Sulfur Dioxide</a></li>
<li><a href="#density"><span class="toc-section-number">2.9</span> Density</a></li>
<li><a href="#ph"><span class="toc-section-number">2.10</span> pH</a></li>
<li><a href="#sulphates"><span class="toc-section-number">2.11</span> Sulphates</a></li>
<li><a href="#alcohol"><span class="toc-section-number">2.12</span> Alcohol</a></li>
</ul></li>
<li><a href="#univariate-analysis"><span class="toc-section-number">3</span> Univariate Analysis</a></li>
<li><a href="#bivariate-exploration-part-i"><span class="toc-section-number">4</span> Bivariate Exploration Part I</a><ul>
<li><a href="#quality-vs-fixed-acidity"><span class="toc-section-number">4.1</span> Quality vs Fixed Acidity</a></li>
<li><a href="#quality-vs-volatile-acidity"><span class="toc-section-number">4.2</span> Quality vs Volatile Acidity</a></li>
<li><a href="#quality-vs-citric-acid"><span class="toc-section-number">4.3</span> Quality vs Citric Acid</a></li>
<li><a href="#quality-vs-residual-sugar"><span class="toc-section-number">4.4</span> Quality vs Residual Sugar</a></li>
<li><a href="#quality-vs-chlorides"><span class="toc-section-number">4.5</span> Quality vs Chlorides</a></li>
<li><a href="#quality-vs-free-sulfur-dioxide"><span class="toc-section-number">4.6</span> Quality vs Free Sulfur Dioxide</a></li>
<li><a href="#quality-vs-total-sulfur-dioxide"><span class="toc-section-number">4.7</span> Quality vs Total Sulfur Dioxide</a></li>
<li><a href="#quality-vs-density"><span class="toc-section-number">4.8</span> Quality vs Density</a></li>
<li><a href="#quality-vs-ph"><span class="toc-section-number">4.9</span> Quality vs pH</a></li>
<li><a href="#quality-vs-sulphates"><span class="toc-section-number">4.10</span> Quality vs Sulphates</a></li>
<li><a href="#quality-vs-alcohol"><span class="toc-section-number">4.11</span> Quality vs Alcohol</a></li>
</ul></li>
<li><a href="#bivariate-exploration-part-ii"><span class="toc-section-number">5</span> Bivariate Exploration Part II</a><ul>
<li><a href="#correlation-matrix"><span class="toc-section-number">5.1</span> Correlation Matrix</a></li>
<li><a href="#fixed-acidity-vs-citric-acid"><span class="toc-section-number">5.2</span> Fixed Acidity vs Citric Acid</a></li>
<li><a href="#volatile-acidity-vs-citric-acid"><span class="toc-section-number">5.3</span> Volatile Acidity vs Citric Acid</a></li>
<li><a href="#ph-vs-log10fixed-acidity"><span class="toc-section-number">5.4</span> pH vs log10(Fixed Acidity)</a></li>
<li><a href="#ph-vs-citric-acid"><span class="toc-section-number">5.5</span> pH vs Citric Acid</a></li>
<li><a href="#total-sulfur-dioxide-vs-free-sulfur-dioxide"><span class="toc-section-number">5.6</span> Total Sulfur Dioxide vs Free Sulfur Dioxide</a></li>
<li><a href="#density-vs-alcohol"><span class="toc-section-number">5.7</span> Density vs Alcohol</a></li>
<li><a href="#density-vs-fixed-acidity"><span class="toc-section-number">5.8</span> Density vs Fixed Acidity</a></li>
</ul></li>
</ul>
</div>

<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>In this report, I will explore the red wine dataset. First, I will look at each individual attribute of this dataset and plot its distribution. Second, I will look at two attributes at a time to explore 1) how each input attribute is related to the output attribute–quality; 2) interesting pairs of input attributes. Third, I will examine three attributes by adding one additional attribute to some of the interesting two-attribute pairs. Finally, I will summarize the successes and problems I encounter during the data exploration process.</p>
<pre class="r"><code># Load all of the packages in this code chunk.
library(ggplot2)
library(corrplot)</code></pre>
<pre class="r"><code># Load the Data
wine_reds = read.csv(&#39;wineQualityReds.csv&#39;, row.names = 1)</code></pre>
</div>
<div id="univariate-exploration" class="section level1">
<h1><span class="header-section-number">2</span> Univariate Exploration</h1>
<p>In this section, I will first look at the structure of the data set. Then I will examine the distribution of each attribute individually by plotting its distribution.</p>
<pre class="r"><code>dim(wine_reds)</code></pre>
<pre><code>## [1] 1599   12</code></pre>
<pre class="r"><code># Convert quality into ordered categorical variable
wine_reds$quality &lt;- ordered(wine_reds$quality)
str(wine_reds)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1599 obs. of  12 variables:
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : Ord.factor w/ 6 levels &quot;3&quot;&lt;&quot;4&quot;&lt;&quot;5&quot;&lt;&quot;6&quot;&lt;..: 3 3 3 4 3 3 3 5 5 3 ...</code></pre>
<pre class="r"><code>summary(wine_reds)</code></pre>
<pre><code>##  fixed.acidity   volatile.acidity  citric.acid    residual.sugar  
##  Min.   : 4.60   Min.   :0.1200   Min.   :0.000   Min.   : 0.900  
##  1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090   1st Qu.: 1.900  
##  Median : 7.90   Median :0.5200   Median :0.260   Median : 2.200  
##  Mean   : 8.32   Mean   :0.5278   Mean   :0.271   Mean   : 2.539  
##  3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420   3rd Qu.: 2.600  
##  Max.   :15.90   Max.   :1.5800   Max.   :1.000   Max.   :15.500  
##    chlorides       free.sulfur.dioxide total.sulfur.dioxide
##  Min.   :0.01200   Min.   : 1.00       Min.   :  6.00      
##  1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 22.00      
##  Median :0.07900   Median :14.00       Median : 38.00      
##  Mean   :0.08747   Mean   :15.87       Mean   : 46.47      
##  3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 62.00      
##  Max.   :0.61100   Max.   :72.00       Max.   :289.00      
##     density             pH          sulphates         alcohol      quality
##  Min.   :0.9901   Min.   :2.740   Min.   :0.3300   Min.   : 8.40   3: 10  
##  1st Qu.:0.9956   1st Qu.:3.210   1st Qu.:0.5500   1st Qu.: 9.50   4: 53  
##  Median :0.9968   Median :3.310   Median :0.6200   Median :10.20   5:681  
##  Mean   :0.9967   Mean   :3.311   Mean   :0.6581   Mean   :10.42   6:638  
##  3rd Qu.:0.9978   3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10   7:199  
##  Max.   :1.0037   Max.   :4.010   Max.   :2.0000   Max.   :14.90   8: 18</code></pre>
<p>The red wine dataset contains 12 variables–11 input numerical variables based on physicochemical tests and 1 categorical output variable (quality) based on sensory data, with 1599 observations.</p>
<pre class="r"><code># Function to plot histogram of a single variable
plot_uni_var &lt;- function(variable, bins = 50) {
  return (ggplot(aes_string(x = variable), data = wine_reds) + 
            geom_histogram(bins = bins))
}</code></pre>
<div id="quality" class="section level2">
<h2><span class="header-section-number">2.1</span> Quality</h2>
<pre class="r"><code>ggplot(aes(x = quality), data = wine_reds) + 
  geom_bar()</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Out of the possible quality scores between 0 and 10, all of our red wines’ quality scores fall between 3 and 8. The dataset is not well balanced. Majority of red wines have a quality score of either 5 or 6. I am curious about what attributes make a wine earn a low quality score (quality = 3) or a high quality score (quality = 8).</p>
</div>
<div id="fixed-acidity" class="section level2">
<h2><span class="header-section-number">2.2</span> Fixed Acidity</h2>
<p>Most acids involved with wine are fixed or nonvolatile (do not evaporate readily).</p>
<pre class="r"><code>plot_uni_var(&#39;fixed.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;fixed.acidity&#39;) + scale_x_log10()</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>Fixed acidity values range between 4 and 16, with most values range between 7 and 9. The distribution is slightly positively skewed. Transforming the x-axis into log scale can make it more normally distributed.</p>
</div>
<div id="volatile-acidity" class="section level2">
<h2><span class="header-section-number">2.3</span> Volatile Acidity</h2>
<p>The amount of acetic acid in wine, which at too high of levels can lead to an unpleasant, vinegar taste.</p>
<pre class="r"><code>plot_uni_var(&#39;volatile.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;volatile.acidity&#39;) + scale_x_continuous(limits = c(0, 1))</code></pre>
<pre><code>## Warning: Removed 21 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<p>Fixed acidity values range between 0.1 and 1.6, with most values range between 0.3 and 0.7. The distribution is slightly positively skewed. When zoom in to values below 1, the distribution seems normal.</p>
</div>
<div id="citric-acid" class="section level2">
<h2><span class="header-section-number">2.4</span> Citric Acid</h2>
<p>Found in small quantities, citric acid can add ‘freshness’ and flavor to wines.</p>
<pre class="r"><code>plot_uni_var(&#39;citric.acid&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code># number of red wines with citric acid = 0
dim(wine_reds[wine_reds$citric.acid ==0, ])[1]</code></pre>
<pre><code>## [1] 132</code></pre>
<p>Citric acid values range between 0 and 1 with most values below 0.6. There are 132 red wines in our data set with no detectable citric acid concentration.</p>
</div>
<div id="residual-sugar" class="section level2">
<h2><span class="header-section-number">2.5</span> Residual Sugar</h2>
<p>The amount of sugar remaining after fermentation stops, it is rare to find wines with less than 1 gram/liter and wines with greater than 45 grams/liter are considered sweet.</p>
<pre class="r"><code>plot_uni_var(&#39;residual.sugar&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;residual.sugar&#39;) + scale_x_continuous(limits = c(0, 5))</code></pre>
<pre><code>## Warning: Removed 84 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p>Most residual sugar values range between 1.5 and 2.5. There are a few outliers with large values. When zoom in and look at values below 5, the distribution appears normal.</p>
</div>
<div id="chlorides" class="section level2">
<h2><span class="header-section-number">2.6</span> Chlorides</h2>
<p>The amount of salt in the wine.</p>
<pre class="r"><code>plot_uni_var(&#39;chlorides&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;chlorides&#39;) + scale_x_continuous(limits = c(0, 0.2))</code></pre>
<pre><code>## Warning: Removed 41 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<p>Most chlorides values range between 0.05 to 0.1. There are a few outliers with large values. When zoom in and look at values below 0.2, the distribution appears normal.</p>
</div>
<div id="free-sulfur-dioxide" class="section level2">
<h2><span class="header-section-number">2.7</span> Free Sulfur Dioxide</h2>
<p>The free form of SO2 exists in equilibrium between molecular SO2 (as a dissolved gas) and bisulfite ion; it prevents microbial growth and the oxidation of wine.</p>
<pre class="r"><code>plot_uni_var(&#39;free.sulfur.dioxide&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The distribution of free sulfur dioxide is highly positively skewed.</p>
</div>
<div id="total-sulfur-dioxide" class="section level2">
<h2><span class="header-section-number">2.8</span> Total Sulfur Dioxide</h2>
<p>The amount of free and bound forms of S02; in low concentrations, SO2 is mostly undetectable in wine, but at free SO2 concentrations over 50 ppm, SO2 becomes evident in the nose and taste of wine.</p>
<pre class="r"><code>plot_uni_var(&#39;total.sulfur.dioxide&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;total.sulfur.dioxide&#39;) + scale_x_log10()</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<p>The distribution of total sulfur dioxide is higly positively skewed. And there are a few outliers with very large values. Transforming the x-axis into log scale can make it more normally distributed.</p>
</div>
<div id="density" class="section level2">
<h2><span class="header-section-number">2.9</span> Density</h2>
<p>The density of wine is close to that of water depending on the percent alcohol and sugar content.</p>
<pre class="r"><code>plot_uni_var(&#39;density&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Density values range between 0.990 and 1.004 with most values range from 0.995 and 0.998. The distribution of density values are symmetrical centered around 0.9965.</p>
</div>
<div id="ph" class="section level2">
<h2><span class="header-section-number">2.10</span> pH</h2>
<p>Describes how acidic or basic a wine is on a scale from 0 (very acidic) to 14 (very basic); most wines are between 3-4 on the pH scale.</p>
<pre class="r"><code>plot_uni_var(&#39;pH&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Most pH values range between 3.15 and 3.45. The distribution of pH is symmetrical centered around 3.3.</p>
</div>
<div id="sulphates" class="section level2">
<h2><span class="header-section-number">2.11</span> Sulphates</h2>
<p>A wine additive which can contribute to sulfur dioxide gas (S02) levels, wich acts as an antimicrobial and antioxidant.</p>
<pre class="r"><code>plot_uni_var(&#39;sulphates&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>plot_uni_var(&#39;sulphates&#39;) + scale_x_log10()</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<p>Most sulphates values range between 0.5 and 0.75. The distribution is positively skewed. There are a few ourliers with large sulphates values. Transforming the x-axis into log scale can make it more normally distributed.</p>
</div>
<div id="alcohol" class="section level2">
<h2><span class="header-section-number">2.12</span> Alcohol</h2>
<p>The percent alcohol content of the wine</p>
<pre class="r"><code>plot_uni_var(&#39;alcohol&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The alcohol values range between 8.5 and 15. The distribution of alcohol value is positively skewed.</p>
</div>
</div>
<div id="univariate-analysis" class="section level1">
<h1><span class="header-section-number">3</span> Univariate Analysis</h1>
<p><strong>What is the structure of your dataset?</strong></p>
<p>There are 12 attributes in the dataset. 11 of them (fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol) are input attributes based on physicochemical tests. The other attribute (quality) is the output attribute based on sensory data. Each row corresponds to one particular wine with total 1599 different red wines in the data set.</p>
<p><strong>What is/are the main feature(s) of interest in your dataset?</strong></p>
<p>The main feature of interest is the output attribute quality. I am trying to figure out which of the 11 input attribute contribute to a high quality value.</p>
<p><strong>What other features in the dataset do you think will help support your investigation into your feature(s) of interest?</strong></p>
<p>The 11 input attributes are equally likely to contribute to the quality value at this point. I will look more closely at how each of the attributes is distributed with a given quality value in the bivariate exploration section.</p>
<p><strong>Did you create any new variables from existing variables in the dataset?</strong></p>
<p>No.</p>
<p><strong>Of the features you investigated, were there any unusual distributions? Did you perform any operations on the data to tidy, adjust, or change the form of the data? If so, why did you do this?</strong></p>
<p>The possible quality values are from 0 to 10, but our data set only has quality values from 3 to 8, which means there are no extremely bad red wines or extrememly good wines in out data set. The vast majority of red wines in the data set has a quality value either 5 or 6, with very fewer wines with quality values 3, 4, 7 or 8, which makes the data set unbalanced.</p>
</div>
<div id="bivariate-exploration-part-i" class="section level1">
<h1><span class="header-section-number">4</span> Bivariate Exploration Part I</h1>
<p>In this section, I will look at how each input attribute is related to the output quanlity variable.</p>
<pre class="r"><code># Function to plot boxplot of variable grouped by quality
plot_quality_vs_var &lt;- function(variable) {
  # Uncomment the next line to print a summary of variable grouped by quality values
  # print (by(wine_reds[[variable]], wine_reds$quality, summary))
  return (ggplot(aes_string(x = &#39;quality&#39;, y = variable), data = wine_reds) + 
            geom_boxplot())
}</code></pre>
<div id="quality-vs-fixed-acidity" class="section level2">
<h2><span class="header-section-number">4.1</span> Quality vs Fixed Acidity</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;fixed.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>There isn’t a clear trend between fixed acidity and quality.</p>
</div>
<div id="quality-vs-volatile-acidity" class="section level2">
<h2><span class="header-section-number">4.2</span> Quality vs Volatile Acidity</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;volatile.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The higher the quality, the lower the volatile acidity.</p>
</div>
<div id="quality-vs-citric-acid" class="section level2">
<h2><span class="header-section-number">4.3</span> Quality vs Citric Acid</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;citric.acid&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The higher the quality, the higher the citric acid.</p>
</div>
<div id="quality-vs-residual-sugar" class="section level2">
<h2><span class="header-section-number">4.4</span> Quality vs Residual Sugar</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;residual.sugar&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>There isn’t a clear trend between residual sugar and quality.</p>
</div>
<div id="quality-vs-chlorides" class="section level2">
<h2><span class="header-section-number">4.5</span> Quality vs Chlorides</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;chlorides&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>plot_quality_vs_var(&#39;chlorides&#39;) + scale_y_continuous(limits = c(0.05, 0.15))</code></pre>
<pre><code>## Warning: Removed 117 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<p>After zoom in, one can see the higher the quality, the lower the chlorides.</p>
</div>
<div id="quality-vs-free-sulfur-dioxide" class="section level2">
<h2><span class="header-section-number">4.6</span> Quality vs Free Sulfur Dioxide</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;free.sulfur.dioxide&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>There isn’t a clear trend between free sulfur dioxide and quality.</p>
</div>
<div id="quality-vs-total-sulfur-dioxide" class="section level2">
<h2><span class="header-section-number">4.7</span> Quality vs Total Sulfur Dioxide</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;total.sulfur.dioxide&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>There isn’t a clear trend between total sulfur dioxide and quality.</p>
</div>
<div id="quality-vs-density" class="section level2">
<h2><span class="header-section-number">4.8</span> Quality vs Density</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;density&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>The higher the quality, the lower the density.</p>
</div>
<div id="quality-vs-ph" class="section level2">
<h2><span class="header-section-number">4.9</span> Quality vs pH</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;pH&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The higher the quality, the lower the pH.</p>
</div>
<div id="quality-vs-sulphates" class="section level2">
<h2><span class="header-section-number">4.10</span> Quality vs Sulphates</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;sulphates&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>The higher the quality, the higher the sulphates.</p>
</div>
<div id="quality-vs-alcohol" class="section level2">
<h2><span class="header-section-number">4.11</span> Quality vs Alcohol</h2>
<pre class="r"><code>plot_quality_vs_var(&#39;alcohol&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>The higher the quality, the higher the alcohol.</p>
</div>
</div>
<div id="bivariate-exploration-part-ii" class="section level1">
<h1><span class="header-section-number">5</span> Bivariate Exploration Part II</h1>
<p>In this section, I will first plot the correlation matrix to find out if there are any interesting pairs of input attributes that look interesting. Then I will examine these pairs.</p>
<div id="correlation-matrix" class="section level2">
<h2><span class="header-section-number">5.1</span> Correlation Matrix</h2>
<pre class="r"><code>cor_matrix &lt;- cor(wine_reds[, 1:11])
corrplot(cor_matrix, type = &#39;lower&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>There are a few pairs of input variables deserve further examing from the correlation matrix plot: fixed acidity vs citric acid, fixed acidity vs density, fixed acidity vs pH, volatile acidity vs citric acid, citric acid vs pH, total sulfur dioxide vs free sulfur dioxide, density vs alcohol.</p>
<pre class="r"><code># Function to plot scatter plot of variable2 vs variable1
plot_bi_var &lt;- function(variable1, variable2) {
  return (ggplot(aes_string(x = variable1, y = variable2), data = wine_reds) + 
    geom_point(alpha = 1/4, position = position_jitter(width = 0)))
}</code></pre>
</div>
<div id="fixed-acidity-vs-citric-acid" class="section level2">
<h2><span class="header-section-number">5.2</span> Fixed Acidity vs Citric Acid</h2>
<pre class="r"><code>plot_bi_var(&#39;citric.acid&#39;, &#39;fixed.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$citric.acid, wine_reds$fixed.acidity)</code></pre>
<pre><code>## [1] 0.6717034</code></pre>
<p>Fixed acidity and citric acid have a correlation coefficient of 0.6717034. This is probably because citric acid is also a kind of fixed acidity.</p>
</div>
<div id="volatile-acidity-vs-citric-acid" class="section level2">
<h2><span class="header-section-number">5.3</span> Volatile Acidity vs Citric Acid</h2>
<pre class="r"><code>plot_bi_var(&#39;citric.acid&#39;, &#39;volatile.acidity&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$citric.acid, wine_reds$volatile.acidity)</code></pre>
<pre><code>## [1] -0.5524957</code></pre>
<p>Volatile acidity and citric acid have a correlation coefficient of -0.5524957. I cannot think of an explaination for this correlation.</p>
</div>
<div id="ph-vs-log10fixed-acidity" class="section level2">
<h2><span class="header-section-number">5.4</span> pH vs log10(Fixed Acidity)</h2>
<pre class="r"><code>plot_bi_var(&#39;log10(fixed.acidity)&#39;, &#39;pH&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre class="r"><code>cor(log10(wine_reds$fixed.acidity), wine_reds$pH)</code></pre>
<pre><code>## [1] -0.7063602</code></pre>
<p>The pH scale is logarithmic, so I first transform fixed acidity into log10(fixed acidity). log10(fixed acidity) and pH have a correlation coefficient of -0.7063602. This is because hihger fixed acidity concentration leads to lower pH values.</p>
</div>
<div id="ph-vs-citric-acid" class="section level2">
<h2><span class="header-section-number">5.5</span> pH vs Citric Acid</h2>
<pre class="r"><code>plot_bi_var(&#39;citric.acid&#39;, &#39;pH&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$citric.acid, wine_reds$pH)</code></pre>
<pre><code>## [1] -0.5419041</code></pre>
<p>Citric acid and pH have a correlation coefficient of -0.5419041. Because we have 132 wines with 0 citric acid values, we cannot perform a logarithmic transfrom here. The correaltion is due to citric acid is non volatile, therefore higher citiric acid concentration leads to lower pH value.</p>
</div>
<div id="total-sulfur-dioxide-vs-free-sulfur-dioxide" class="section level2">
<h2><span class="header-section-number">5.6</span> Total Sulfur Dioxide vs Free Sulfur Dioxide</h2>
<pre class="r"><code>plot_bi_var(&#39;free.sulfur.dioxide&#39;, &#39;total.sulfur.dioxide&#39;) + geom_abline(slope=1)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$free.sulfur.dioxide, wine_reds$total.sulfur.dioxide)</code></pre>
<pre><code>## [1] 0.6676665</code></pre>
<p>Total sulfur dioxide and free sulfur dioxide have a correlation coefficient of 0.6676665. This is because free sulfur dioxide is part of total sulfur dioxide, and this can also be seen from all the points are above the y=x line.</p>
</div>
<div id="density-vs-alcohol" class="section level2">
<h2><span class="header-section-number">5.7</span> Density vs Alcohol</h2>
<pre class="r"><code>plot_bi_var(&#39;alcohol&#39;, &#39;density&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$alcohol, wine_reds$density)</code></pre>
<pre><code>## [1] -0.4961798</code></pre>
<p>Density and alcohol have a correlation coefficient of -0.4961798. This is probably because alcohol has a lower density comparing to water. Therefore, the higher concentration of alcohol, the lower the wine density is.</p>
</div>
<div id="density-vs-fixed-acidity" class="section level2">
<h2><span class="header-section-number">5.8</span> Density vs Fixed Acidity</h2>
<pre class="r"><code>plot_bi_var(&#39;fixed.acidity&#39;, &#39;density&#39;)</code></pre>
<p><img src="udacity_dand-p4-explore-and-summarize-data_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<pre class="r"><code>cor(wine_reds$fixed.acidity, wine_reds$density)</code></pre>
<pre><code>## [1] 0.6680473</code></pre>
<p>Densidy and fixed acidity have a correlation coefficient of 0.6680473. This is probably because fixed acidity in wine is mainly tartaric acid, and tartaric acid has a density of 1.79 g/mL, which is greater than the wine’s main component–water. Therefore, higher concentration of fixed acidity leads to higher density value.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
